name: login_signin
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.12.0 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  conditional_builder_null_safety: ^0.0.6
  dio: ^4.0.4
  hexcolor: ^2.0.6
  shared_preferences: ^2.0.12
  webview_flutter: ^3.0.0
  google_fonts: ^2.2.0
  provider: ^6.0.2
  get: ^4.6.1
  smooth_page_indicator: ^1.0.0+2
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^3.2.4
  sk_onboarding_screen: ^1.0.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.8
  toast: ^0.1.5
  carousel_slider: ^4.0.0
  iconsax: ^0.0.8
  flutter_launcher_icons: ^0.9.2
  sliding_up_panel: ^2.0.0+1
  cupertino_icons: ^1.0.4
dev_dependencies:
  flutter_test: {sdk: flutter}
flutter:
  uses-material-design: true
  assets: ['assetsD:\Programming\My Work\Flutter Apps\smart_education_   test\assets/']
  fonts: []
