// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF55VJtCtLjku4BEDYZyrCeQqi0kV9UuU',
    appId: '1:148534944195:web:88f85c4e95bf4f358cdd76',
    messagingSenderId: '148534944195',
    projectId: 'ses-graduation',
    authDomain: 'ses-graduation.firebaseapp.com',
    storageBucket: 'ses-graduation.appspot.com',
    measurementId: 'G-3T1RRKERSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYoFHLS560gLBwuD_e6eHsLWnkbMOw2c',
    appId: '1:148534944195:android:748c75a5792bf8db8cdd76',
    messagingSenderId: '148534944195',
    projectId: 'ses-graduation',
    storageBucket: 'ses-graduation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlnT4FbOGFib9tHnDDMWlDn7bCbxEBzHo',
    appId: '1:148534944195:ios:d22db918481cd1798cdd76',
    messagingSenderId: '148534944195',
    projectId: 'ses-graduation',
    storageBucket: 'ses-graduation.appspot.com',
    iosClientId: '148534944195-co8b28hmmpl3k0dq8o768pum3k633f7q.apps.googleusercontent.com',
    iosBundleId: 'com.smartedu.app',
  );
}
